hobbysite/blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView
    )

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path(
        'article/<int:pk>/',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'article/add/',
        ArticleCreateView.as_view(),
        name='article_create'
    ),
    path(
        'article/<int:pk>/edit',
        ArticleUpdateView.as_view(),
        name='article_edit'
    )
]

app_name = "blog"

hobbysite/commissions/urls.py
from django.urls import path
from .views import ComListView, ComDetailView, ComCreateView, ComUpdateView, JobDetailView, JobAddView

urlpatterns = [
    path('list', ComListView.as_view(), name='list'),
    path('detail/<int:pk>', ComDetailView.as_view(), name='detail'),
    path('add', ComCreateView.as_view(), name='add'),
    path('<int:pk>/edit', ComUpdateView.as_view(), name='edit'),
    path('job/<int:pk>', JobDetailView.as_view(), name='job_detail'),
    path('<int:pk>/add-job', JobAddView.as_view(), name='job_add'),
]

app_name = 'commissions'

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profile.urls', namespace='profile')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/commissions/models.py
from django.db import models
from django.urls import reverse
from profile.models import Profile


class Commission(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(Profile,
                            on_delete=models.CASCADE,
                            related_name="author",
                            null=True)
    STATUS_CHOICES = (
        ('Open', 'Open'),
        ('Full', 'Full'),
        ('Completed', 'Completed'),
        ('Discontinued', 'Discontinued'),
    )
    status = models.CharField(max_length=14, choices=STATUS_CHOICES, default='Open')
    people_required = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('commissions:detail', args=[self.pk])

    class Meta:
        ordering = ['status', 'created_on']

        verbose_name = 'commission'
        verbose_name_plural = 'commissions'


class Job(models.Model):
    commission = models.ForeignKey(Commission,
                                   on_delete=models.CASCADE,
                                   related_name='job')
    role = models.CharField(max_length=255)
    manpower_required = models.IntegerField()
    STATUS_CHOICES = [
        ('open', 'Open'),
        ('full', 'Full'),
    ]
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='open')
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-status', '-manpower_required', 'role']

        verbose_name = 'job'
        verbose_name_plural = 'jobs'


class JobApplication(models.Model):
    job = models.ForeignKey(Job,
                            on_delete=models.CASCADE,
                            related_name='job')
    applicant = models.ForeignKey(Profile,
                                  on_delete=models.CASCADE,
                                  related_name='applicant',
                                  null=True) #TODO: TEMP
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    applied_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['status', 'applied_on']

        verbose_name = 'job application'
        verbose_name_plural = 'job applications'

hobbysite/commissions/forms.py
from django import forms
from .models import Commission, Job, JobApplication


class CommissionForm(forms.ModelForm):
    class Meta:
        model = Commission
        fields = '__all__'


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ['commission']


class JobAppForm(forms.ModelForm):
    class Meta:
        model = JobApplication
        exclude = ['job', 'applicant', 'status']
        

hobbysite/commissions/views.py
from .models import Commission, Job, JobApplication
from .forms import JobForm, JobAppForm
from django.db.models import  Case, When
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from profile.models import Profile
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect


class ComListView(ListView):
    model = Commission
    template_name = 'commission-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sorted_comms = Commission.objects.annotate(
            ordering = Case(
                When(status='Open', then=0),
                When(status='Full', then=1),
                When(status='Completed', then=2),
                When(status='Discontinued', then=3)
            )
        ).order_by('ordering')

        context['created_comms'] = []
        for comm in sorted_comms:
            if comm.author.user == Profile.objects.get(user=self.request.user):
                context['created_comms'].append(comm)

        context['applied_comms'] = []
        for jobApp in JobApplication.objects.all():
            if jobApp.applicant == Profile.objects.get(user=self.request.user):
                context['applied_comms'].append(jobApp.job.commission)

        context['sorted_comms'] = sorted_comms
        return context
    

class ComDetailView(DetailView):
    model = Commission
    template_name = 'commission-detail.html'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('commissions:detail', args=[self.pk])

    def get_context_data(self, **kwargs):
        context = super(ComDetailView, self).get_context_data(**kwargs)
        context['total_manpower'] = 0
        for job in Job.objects.all():
            if job.commission == self.get_object():
                context['total_manpower'] += job.manpower_required

        context['open_manpower'] = context['total_manpower']
        for jobApp in JobApplication.objects.all():
            if jobApp.job.commission == self.get_object():
                if jobApp.status == 'Accepted':
                    context['open_manpower'] -= 1

        context['form'] = JobAppForm()
        context['job'] = Job()
        context['jobApp_list'] = JobApplication.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form = JobAppForm(request.POST)
        if form.is_valid():
            form.instance.applicant = Profile.objects.get(user=self.request.user)
            form.instance.job = self.get_object()

            form.save()
            return self.get(request, *args, **kwargs)
        else:
            self.object_list = self.get_queryset(**kwargs)
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)
        

class JobDetailView(LoginRequiredMixin, DetailView):
    model = Job
    template_name = 'job-detail.html'
    redirect_field_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = JobAppForm()
        context['jobApps'] = []
        context['acceptedJobApps'] = []
        for jobApp in JobApplication.objects.all():
            if jobApp.job == self.get_object():
                context['jobApps'].append(jobApp)
            if jobApp.status == 'Accepted' and jobApp.job == self.get_object():
                context['acceptedJobApps'].append(jobApp)
        context['acceptedJobAppCount'] = len(context['acceptedJobApps'])

        return context
    
    def post(self, request, *args, **kwargs):
        form = JobAppForm(request.POST)
        if form.is_valid():
            form.instance.applicant = Profile.objects.get(user=self.request.user)
            form.instance.job = self.get_object()
            form.save()
            return self.get(request, *args, **kwargs)
        else:
            self.object_list = self.get_queryset(**kwargs)
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)


class JobAddView(LoginRequiredMixin, DetailView):
    model = Commission
    template_name = 'job-add.html'
    redirect_field_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = JobForm()
        context['all_objects'] = Commission.objects.all()
        return context

    def get_success_url(self):
        return reverse('commissions:detail', kwargs={'pk': self.object.pk})
    
    def post(self, request, *args, **kwargs):
        form = JobForm(request.POST)
        if form.is_valid():
            form.instance.commission = self.get_object()
            form.save()
            return redirect('commissions:detail', pk=self.get_object().pk)
        else:
            self.object_list = self.get_queryset(**kwargs)
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)
    
    


class ComCreateView(LoginRequiredMixin, CreateView):
    model = Commission
    template_name = 'commission-add.html'
    redirect_field_name = 'login.html'
    fields = ['title', 'description']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        form.instance.author = Profile.objects.get(user=self.request.user)
        return super(ComCreateView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse('commissions:job_add', kwargs={'pk': self.object.pk})


class ComUpdateView(LoginRequiredMixin, UpdateView):
    model = Commission
    fields = ['title', 'description', 'status']
    template_name = 'commission-update.html'
    redirect_field_name = 'login.html'
    

hobbysite/commissions/templates/commission-add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Commission Add{% endblock %}


{% block content %}
<div class="container">
    <h1>Create a Commission</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create</button>
    </form>
</div>
{% endblock %}

hobbysite/commissions/templates/commission-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <a href={% url 'commissions:list' %}>Commission List</a>
    <h1>{{ commission.title }}</h1>
    <p style="margin-right:350px">{{ commission.description }}</p>
    <hr style="margin-top:30px;">
    <div class="card" style="width: 40rem; margin-top:30px">
        <div class="card-body">
            <div class="row justify-content-start">
                <div class="col"><b>Author</b> <p>{{ commission.author.display_name }}</p></div>
                <div class="col"><b>People Required</b> <p>{{ total_manpower}}</p></div>
                <div class="col"><b>Open Positions</b> <p>{{ open_manpower }}</p></div>
            </div>
            <br>
            <div class="row justify-content-start">
                <div class="col"><b>Status</b> <p>{{ commission.status }}</p></div>
                <div class="col"><b>Created on</b> <p>{{ commission.created_on }}</p></div>
                <div class="col"><b>Last updated</b> <p>{{ commission.updated_on }}</p></div>
            </div>
        </div>
    </div>
    <br>
    <a href={% url 'commissions:edit' pk=object.pk %} class='btn btn-warning'>Edit Commission</a>
    <hr style="margin-top:30px;">
</div>    
<br>

<div class="container">
    <h2>Jobs</h2>
        {% for job in commission.job.all %}

        <div class="card" style="width: 32rem">
            <div class="card-header"><b>{{ job.role }}</b></div>
            <div class="card-body">
                <p class="card-text">{{ job.entry }}</p>
                <br>
                <div class="row justify-content-start">
                    <div class="col"><b>Status</b> <p>{{ job.status }}</p></div>
                    <div class="col"><b>Manpower Required</b> <p>{{ job.manpower_required }}</p></div>
                </div>
                {% if commission.author.user == user %}
                    <a href={% url 'commissions:job_detail' pk=job.pk %} class="btn btn-warning">View Job Details & Review Applications</a>
                {% else %}
                    <a href={% url 'commissions:job_detail' pk=job.pk %} class="btn btn-primary">View Job Details & Apply</a>
                {% endif %}
            </div>
        </div>
        <br>
        {% endfor %}
</div>
{% endblock %}

hobbysite/commissions/templates/commission-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <div class="row justify-content-start">
        <div class="col">
            <div class="container">
                <h2>Your Commissions</h2>
                <hr>
                <a href={% url 'commissions:add' %} class="btn btn-warning" style="margin-bottom:30px;">Create Commission</a>
                {% for commission in created_comms %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-header">{{ commission.title }}</div>
                        <div class="card-body">
                            <p class="card-text">Status: {{ commission.status}}</p>
                            <a href="{{ commission.get_absolute_url }}" class="btn btn-primary btn-sm">Details</a>
                        </div>    
                    </div>
                    <br><br>
                {% endfor %}
            </div>
        </div>

        <div class="col">    
            <div class="container">
                <h2>Applied Commissions</h2>
                <hr>
                {% for commission in applied_comms %}
                <div class="card" style="width: 18rem;">
                    <div class="card-header">{{ commission.title }}</div>
                    <div class="card-body">
                        <p class="card-text">Status: {{ commission.status}}</p>
                        <a href="{{ commission.get_absolute_url }}" class="btn btn-primary btn-sm">Details</a>
                    </div>    
                </div>
                <br><br>
                {% endfor %}
            </div>
    </div>
</div>
{% endif %}

<div class="container">
    <h2>Commissions</h2>
    {% for commission in sorted_comms %}
    <div class="card" style="width: 18rem;">
        <div class="card-header">{{ commission.title }}</div>
        <div class="card-body">
            <p class="card-text">Status: {{ commission.status}}</p>
            <a href="{{ commission.get_absolute_url }}" class="btn btn-primary btn-sm">Details</a>
        </div>    
    </div>
    <br><br>
    {% endfor %}
</div>

{% endblock %}

hobbysite/commissions/templates/commission-update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Commission Edit{% endblock %}


{% block content %}
<h1>Edit Commission</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>
    
{% endblock %}

hobbysite/commissions/templates/job-add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Job Add{% endblock %}


{% block content %}
<div class="container">
    <h1>Add Jobs to your Commission</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create</button>
    </form>
</div>
{% endblock %}

hobbysite/commissions/templates/job-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h2>Job Details</h2>
    <div class="card" style="width: 40rem; margin-top:30px">
        <div class="card-body">
            <div class="row justify-content-start">
                <div class="col"><b>Role</b> <p>{{ job.role }}</p></div>
                <div class="col"><b>Manpower Required</b> <p>{{ job.manpower_required }}</p></div>
                <div class="col"><b>Status</b> <p>{{ job.status }}</p></div>
            </div>
            <br>
            <div class="row justify-content-start">
                <div class="col"><b>Commission</b> <p>{{ job.commission.title }}</p></div>
                <div class="col"><b>Job Created on</b> <p>{{ job.created_on }}</p></div>
                <div class="col"><b>Last updated</b> <p>{{ job.updated_on }}</p></div>
            </div>
            <div class="row justify-content-start">
                <hr>
                <div class="col"><b>Details</b> <p>{{ job.entry }}</p></div>
            </div>
        </div>
    </div>
</div>
<br>
<hr>
{% if job.commission.author.user != user %}
<div class="container">
    <h2>Apply to Job</h2>
    {% if acceptedJobAppCount != job.manpower_required %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Apply</button>
    </form>
    {% else %}
    <p> Job Slots are Full! </p>
    {% endif %}
</div>
{% else %}
<div class="container">
    <h2>Job Applications</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Applicant</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for jobApp in jobApps %}
            <tr>
                <td>{{ jobApp.status }}</td>
                <td>{{ jobApp.applicant }}</td>
                <td><a href='' class="btn btn-warning">Review Application</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}