hobbysite/blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView
    )

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path(
        'article/<int:pk>/',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'article/add/',
        ArticleCreateView.as_view(),
        name='article_create'
    ),
    path(
        'article/<int:pk>/edit',
        ArticleUpdateView.as_view(),
        name='article_edit'
    )
]

app_name = "blog"

hobbysite/commissions/urls.py
from django.urls import path
from .views import ComListView, ComDetailView, ComCreateView, ComUpdateView, JobDetailView, JobAddView

urlpatterns = [
    path('list', ComListView.as_view(), name='list'),
    path('detail/<int:pk>', ComDetailView.as_view(), name='detail'),
    path('add', ComCreateView.as_view(), name='add'),
    path('<int:pk>/edit', ComUpdateView.as_view(), name='edit'),
    path('job/<int:pk>', JobDetailView.as_view(), name='job_detail'),
    path('<int:pk>/add-job', JobAddView.as_view(), name='job_add'),
]

app_name = 'commissions'

hobbysite/forum/urls.py
from django.urls import path
from .views import (
    ThreadListView,
    ThreadDetailView,
    ThreadCreateView,
    ThreadUpdateView
)


urlpatterns = [
    path(
        'threads/',
        ThreadListView.as_view(),
        name='thread_list'
    ),
    path(
        'thread/<int:pk>/',
        ThreadDetailView.as_view(),
        name='thread_detail'
    ),
    path(
        'thread/add/',
        ThreadCreateView.as_view(),
        name='thread_create'
    ),
    path(
        'thread/<int:pk>/edit/',
        ThreadUpdateView.as_view(),
        name='thread_update'
    ),
]

app_name = "forum"

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profile.urls', namespace='profile')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/merchstore/urls.py
from django.urls import path
from .views import IndividProductView, AllItemsView, ProductCreateView, ProductUpdateView, CartView, TransactionView

urlpatterns = [
    path(
        'items',
        AllItemsView.as_view(),
        name="items"
        ),
    path(
        'item/<int:pk>',
        IndividProductView.as_view(),
        name="itempage"
        ),
    path(
        'item/add',
        ProductCreateView.as_view(),
        name="itemcreate"
        ),
    path(
        'item/<int:pk>/edit',
        ProductUpdateView.as_view(),
        name="itemupdate"
        ),
    path(
        'cart',
        CartView.as_view(),
        name="cart"
        ),
    path(
        'transactions',
        TransactionView.as_view(),
        name="sellertransactions"
        ),
]

app_name = "merchstore"

hobbysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Hobby Site</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
	</head>
	<body>
		<a href="{% url 'homepage' %}" class="btn btn-primary">Home</a>
		<a href="{% url 'admin:index' %}" class="btn btn-primary">Admin</a>
		Logged in as: {{ user }}
		{% block content %}{% endblock %}
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
	</body>
</html>

hobbysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
	<html>
		<div class="container text-center">
		
			<div class="row">
				<div class="col">
					<h1>Hobby Site</h1>
				</div>
			</div>
			
			<div class="row">
				<div class="col">
					<div class="d-grid gap-2">
						<a href="{% url 'merchstore:items' %}" class="btn btn-warning btn-lg text-nowrap">Merchandise Store</a>
						<a href="{% url 'wiki:article_list' %}" class="btn btn-warning btn-lg text-nowrap">Wiki</a>
						<a href="{% url 'blog:article_list' %}" class="btn btn-warning btn-lg text-nowrap">Blog</a>
						<a href="{% url 'forum:thread_list' %}" class="btn btn-warning btn-lg text-nowrap">Forum</a>
						<a href="{% url 'commissions:list' %}" class="btn btn-warning btn-lg text-nowrap">Commission Board</a>
						Your Dashboard
						
						{% if not user.is_authenticated %}
							<a href="{% url 'login' %}" class="btn btn-primary">Log in</a>
						{% else %}
							<form method="POST" action="{% url 'logout' %}">
							    {% csrf_token %}
							    <input type="submit" value="Logout">
							</form>
						{% endif %}
						<a href="{% url 'profile:profile_create' %}" class="btn btn-warning btn-lg text-nowrap">Register Here</a>
					</div>
			</div>
		</div>
	</html>
{% endblock %}


  