hobbysite/blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView
    )

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path(
        'article/<int:pk>/',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'article/add/',
        ArticleCreateView.as_view(),
        name='article_create'
    ),
    path(
        'article/<int:pk>/edit',
        ArticleUpdateView.as_view(),
        name='article_edit'
    )
]

app_name = "blog"

hobbysite/forum/urls.py
from django.urls import path
from .views import (
    ThreadListView,
    ThreadDetailView,
    ThreadCreateView,
    ThreadUpdateView
)


urlpatterns = [
    path(
        'threads/',
        ThreadListView.as_view(),
        name='thread_list'
    ),
    path(
        'thread/<int:pk>/',
        ThreadDetailView.as_view(),
        name='thread_detail'
    ),
    path(
        'thread/add/',
        ThreadCreateView.as_view(),
        name='thread_create'
    ),
    path(
        'thread/<int:pk>/edit/',
        ThreadUpdateView.as_view(),
        name='thread_update'
    ),
]

app_name = "forum"

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profile.urls', namespace='profile')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/forum/models.py
from django.db import models
from django.urls import reverse
from profile.models import Profile


class ThreadCategory(models.Model):
    name = models.CharField(max_length=255, null=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Thread Categories"


class Thread(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        editable=False
    )
    category = models.ForeignKey(
        ThreadCategory,
        on_delete=models.SET_NULL,
        null=True
    )
    entry = models.TextField()
    optional_image = models.ImageField(
        upload_to='media/images/',
        blank=True,
        null=True,
        verbose_name="Optional Image",
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:thread_detail', args=[self.pk])

    class Meta:
        ordering = ['-created_on']


class Comment(models.Model):
    author = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        related_name="forum_comments"
    )
    thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_on']

hobbysite/forum/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['entry']

hobbysite/forum/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from profile.models import Profile
from .models import ThreadCategory, Thread
from .forms import CommentForm


class ThreadListView(ListView):
    model = ThreadCategory
    template_name = 'thread_list.html'


class ThreadDetailView(DetailView):
    model = Thread
    template_name = 'thread_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ThreadDetailView, self).get_context_data(**kwargs)
        context['all_objects'] = Thread.objects.all()
        context['form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.author = Profile.objects.get(user=self.request.user)
            form.instance.thread = self.get_object()
            form.save()
            return self.get(request, *args, **kwargs)
        else:
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)


class ThreadCreateView(LoginRequiredMixin, CreateView):
    model = Thread
    fields = ['title', 'category', 'entry', 'optional_image']
    template_name = 'thread_form.html'

    def form_valid(self, form):
        user = Profile.objects.get(user=self.request.user)
        form.instance.author = user
        return super(ThreadCreateView, self).form_valid(form)


class ThreadUpdateView(LoginRequiredMixin, UpdateView):
    model = Thread
    fields = ['title', 'category', 'entry', 'optional_image']
    template_name = 'thread_form.html'

hobbysite/forum/templates/thread_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
	 <div class="row">
		<div class="col-md-8 mb-3">
			<div class="card text-center border-info">
				<div class="card-body">
					<h5 class="card-title">{{ thread.title }}</h5>
					<p class="card-text">{{ thread.entry }}</p>
				</div>
				{% if thread.optional_image %}
					<img src="{{ thread.optional_image.url }}" 
					   class="card-img-bottom img-fluid"
					   style="max-height: 300px; object-fit: contain;"
					   alt="...">
					<br>
				{% endif %}
				{% if user == thread.author.user %}
					<h3><a href="{% url 'forum:thread_update' pk=thread.pk %}" class="btn btn-warning">Edit</a></h3>
				{% endif %}
			</div>
		</div>

		<div class="col-md-4 mb-3">
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col"><b>Author</b><p>{{ thread.author.display_name }}</p></div>
						<div class="col"><b>Category</b><p>{{ thread.category.name }}</p></div>
					</div>
					<br>
					<div class="row">
						<div class="col"><b>Created on</b><p>{{ thread.created_on }}</p></div>
						<div class="col"><b>Last updated</b><p>{{ thread.updated_on }}</p></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
		
<div class="container mt-4">
	<div class="row">
		<div class="col-md-8 mb-3">
			<div class="card border-warning">
				<div class="card-body">
					<h2>Comments</h2>
					<ol>
						{% for comment in thread.comments.all %}
							<li>
								{{ comment.author.display_name }}: {{ comment.entry }}<br>
								Commented on: {{ comment.created_on }}
							</li>
							{% empty %}
							<p>No comments yet.</p>
						{% endfor %}
					</ol>
			  
					{% if user.is_authenticated %}
						<form method="post">
							{% csrf_token %}
							{{ form.as_p }}
							<input type="submit" value="Submit" class="btn btn-warning">
						</form>
					{% endif %}
				</div>
			</div>
		</div>
	
		<div class="col-md-4 mb-3">
			<div class="card">
				<div class="card-body">
					<h2>Other threads in {{ thread.category }}</h2>
					<ul class="list-unstyled">
					{% for other_thread in all_objects %}
						{% if other_thread.category == thread.category and other_thread.title != thread.title %}
							<li>
							  <a href="{{ other_thread.get_absolute_url }}">{{ other_thread.title }}</a>
							</li>
						{% endif %}
					{% endfor %}
					<a href="{% url 'forum:thread_list' %}" class="btn btn-primary">Back to Threads</a>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
		
{% endblock %}

hobbysite/forum/templates/thread_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center">

	<form method="post"enctype="multipart/form-data">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit" class="btn btn-warning">
	</form>

	<a href="{% url 'forum:thread_list' %}" class="btn btn-primary">Back to Threads</a>
	
</div>

{% endblock %}

hobbysite/forum/templates/thread_list.html
{% extends 'base.html' %}

{% block content %}
	
	<div class="container text-center">
		<h1>Forum Threads</h1>
		<br><br><br>
	</div>
	
	
	<div class="container text-left">
		
		<div class="row">
			<div class="col">
				<h2>Your Threads</h2>
				{% for category in object_list %}
					<h3>{{ category.name }}</h3>
					<p>{{ category.description }}</p>
					<ul>
						{% for thread in category.thread_set.all %}
							{% if thread.author.user == user %}
									<li><a href="{{ thread.get_absolute_url }}">{{ thread.title }}</a>
									by {{ thread.author.display_name }}</li>
							{% endif %}
						{% endfor %}
					</ul>
				{% endfor %}
			</div>
			<div class="col">
				<h2>All Threads</h2>
				{% for category in object_list %}
					<h3>{{ category.name }}</h3>
					<p>{{ category.description }}</p>
					<ul>
						{% for thread in category.thread_set.all %}
							{% if thread.author.user != user %}
									<li><a href="{{ thread.get_absolute_url }}">{{ thread.title }}</a>
									by {{ thread.author.display_name }}</li>
							{% endif %}
						{% endfor %}
					</ul>
				{% endfor %}
			</div>
		</div>
		
		<a href="{% url 'forum:thread_create' %}" class="btn btn-warning">Create a Thread</a>
	</div>
	
{% endblock %}