hobbysite/blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView
    )

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article_list'),
    path(
        'article/<int:pk>/',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        'article/add/',
        ArticleCreateView.as_view(),
        name='article_create'
    ),
    path(
        'article/<int:pk>/edit',
        ArticleUpdateView.as_view(),
        name='article_edit'
    )
]

app_name = "blog"

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .views import homepage

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profile.urls', namespace='profile')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/merchstore/urls.py
from django.urls import path
from .views import IndividProductView, AllItemsView, ProductCreateView, ProductUpdateView, CartView, TransactionView

urlpatterns = [
    path(
        'items',
        AllItemsView.as_view(),
        name="items"
        ),
    path(
        'item/<int:pk>',
        IndividProductView.as_view(),
        name="itempage"
        ),
    path(
        'item/add',
        ProductCreateView.as_view(),
        name="itemcreate"
        ),
    path(
        'item/<int:pk>/edit',
        ProductUpdateView.as_view(),
        name="itemupdate"
        ),
    path(
        'cart',
        CartView.as_view(),
        name="cart"
        ),
    path(
        'transactions',
        TransactionView.as_view(),
        name="sellertransactions"
        ),
]

app_name = "merchstore"

hobbysite/merchstore/models.py
from django.db import models
from django.urls import reverse
from profile.models import Profile


# Create your models here.
class ProductType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']


class Product(models.Model):
    name = models.CharField(max_length=255)
    product_type = models.ForeignKey(
            ProductType,
            on_delete=models.SET_NULL,
            null=True,
            related_name="product"
            )
    owner = models.ForeignKey(
            Profile,
            on_delete=models.CASCADE,
            null=True,
            related_name="owner"
            )
    description = models.TextField()
    price = models.DecimalField(max_digits=999999999, decimal_places=2)
    stock = models.IntegerField(default=0)
    status_choices = {
        'Out of Stock': 'NO_STOCK',
        'On Sale': 'SALE',
        'Available': 'STOCK',
    }
    status = models.CharField(
        max_length=255,
        choices=status_choices,
        default='AVAILABLE'
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        unique_together = ['name', 'product_type', 'description', 'price']
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('merchstore:itempage', args=[self.pk])


class Transaction(models.Model):
    buyer = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        related_name="buyer"
        )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        null=True,
        related_name="item"
        )
    amount = models.IntegerField()
    status_choices = {
        'On cart': 'CART',
        'To Pay': 'PAY',
        'To Ship': 'SHIPPING',
        'To Recieve': 'TRANSIT',
        'Delivered': 'DONE'
    }
    status = models.CharField(
        max_length=255,
        choices=status_choices,
        default='CART'
        )
    created_on = models.DateTimeField(auto_now_add=True)

hobbysite/merchstore/forms.py
from django import forms
from .models import Product, Transaction


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['owner']


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['owner']


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount']

hobbysite/merchstore/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from .models import Product, ProductType, Transaction
from .forms import ProductCreateForm, ProductUpdateForm, TransactionForm
from profile.models import Profile


class IndividProductView(DetailView):
    model = Product
    template_name = 'merchstore/itempage.html'

    def get_context_data(self, **kwargs):
        context = super(IndividProductView, self).get_context_data(**kwargs)
        context['all_objects'] = Product.objects.all()
        context['form'] = TransactionForm()
        context['cart'] = reverse_lazy('merchstore:cart')
        return context

    def post(self, request, *args, **kwargs):
        form = TransactionForm(request.POST)
        product = Product.objects.get(pk=self.kwargs['pk'])
        if form.is_valid():
            form.instance.product = product
            form.instance.status = 'On cart'
            form.instance.amount = request.POST.get('amount')
            product.stock -= int(form.instance.amount)
            if product.stock < 1:
                product.status = 'Out of Stock'
            if not (request.user.is_authenticated):
                return redirect('login')
            form.instance.buyer = Profile.objects.get(user=self.request.user)
            product.save()
            form.save()
            return redirect('merchstore:cart')
        else:
            self.object_list = self.get_queryset(**kwargs)
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)


class AllItemsView(ListView):
    model = ProductType
    template_name = 'merchstore/items.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'merchstore/productform.html'
    redirect_field_name = '/accounts/login'

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user=self.request.user)
        if form.instance.stock < 1:
            form.instance.status = 'Out of Stock'
        else:
            form.instance.status = 'Available'
        return super(ProductCreateView, self).form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name = 'merchstore/productform.html'
    redirect_field_name = '/accounts/login'

    def form_valid(self, form):
        form.instance.owner = Profile.objects.get(user=self.request.user)
        if form.instance.stock < 1:
            form.instance.status = 'Out of Stock'
        else:
            form.instance.status = 'Available'
        return super(ProductUpdateView, self).form_valid(form)


class CartView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'merchstore/cart.html'
    redirect_field_name = '/accounts/login'

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context['sellers'] = Profile.objects.all()
        return context


class TransactionView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'merchstore/transactions.html'
    redirect_field_name = '/accounts/login'
    
    def get_context_data(self, **kwargs):
        context = super(TransactionView, self).get_context_data(**kwargs)
        context['buyers'] = Profile.objects.all()
        return context

hobbysite/merchstore/templates/merchstore/base.html
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% if request.user.is_authenticated %}
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
    {% block styles %}{% endblock %}
</head>
<body>
    <h1> Merch Store </h1>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>

hobbysite/merchstore/templates/merchstore/cart.html
{% extends 'merchstore/base.html' %}
{% load static %}
{% block title %} Cart {% endblock %}
{% block content %}

<ul>
<h2>Your Cart</h2>
  {% for seller in sellers %}
    <dl>
      {% if seller.user != user %}
      <dt><h3>Sold by {{seller.display_name}}</h3></dt>
      {% endif %}
    </dl>
    <ol>
    {% for transaction in object_list %}
      {% if transaction.product.owner == seller %}
        {% if transaction.buyer.user == user %}
          <li><strong>{{transaction.product.name}} ({{transaction.status}})</strong> </li>
            <ul>
              <li>{{transaction.amount}} item(/s)</li>
            </ul>
        {% endif %}
      {%endif%}
    {% endfor %}
    </ol>
  {% endfor %}
</ul>

<a href="{% url 'merchstore:items' %}">Return to Product Listings</a>


{% endblock %}

hobbysite/merchstore/templates/merchstore/itempage.html
{% extends 'merchstore/base.html' %}
{% load static %}
{% block title %} Product {% endblock %}
{% block content %}


<h2> {{product.name}} </h2>
<i> Sold by: {{product.owner.display_name}} </i> <br>
<i> Php <strong>{{product.price}}</strong></i> <br>
<br>
<strong>Description:</strong> {{product.description}}
<br>
<strong>Stock:</strong> {{product.stock}}


<dl>
    <dt><i>Category:</i> <strong>{{product.product_type.name}}</strong></dt>
    <dd>{{product.product_type.description}}</dd>
</dl>

{% if user != product.owner.user %}
    <form method = "POST">
        {% csrf_token %}
        {{form}}
        {% if product.stock > 0 %}
            <button type = "submit" value = "Submit">Buy</button>
        {% else %}
            <button type="submit" disabled>Buy</button>
        {% endif %}
    </form>
{% endif %}

{% if request.user.is_authenticated %}
    {% if user == product.owner.user %}
        <a href="{{object.get_absolute_url}}/edit">Edit Item Information</a>
    {% endif %}
{% endif %}

<br>
<a href="{% url 'merchstore:items' %}">Return to Product Listings</a>


{% endblock %}

hobbysite/merchstore/templates/merchstore/items.html
{% extends 'merchstore/base.html' %}
{% load static %}
{% block title %} Merchandise {% endblock %}
{% block content %}

<ul>

<a href="{% url 'merchstore:itemcreate' %}">Add an Item</a>

{% if request.user.is_authenticated %}
  <h2>Your Products</h2>
    {% for product_type in object_list %}
      <dl>
        <dt><h3>{{product_type}}</h3></dt>
        <dd><i>{{product_type.description}}</i></dd>
      </dl>
      <ol>
        <h4>Items</h4>
          {% for product in product_type.product.all %}
            {% if product.owner.user == user %}
              <li><strong><a href='{{product.get_absolute_url}}'>{{product.name}} </strong> from {{product.owner.display_name}}</a>:<i>({{product.status}})</i></li>
              <ul>
                <li>{{product.description}}
              </ul>
            {% endif %}
          {% endfor %}
      </ol>
      <a href="{% url 'merchstore:sellertransactions' %}">Transactions</a>
    {% endfor %}
    
  <h2>All Products</h2>
    {% for product_type in object_list %}
      <dl>
        <dt><h3>{{product_type}}</h3></dt>
        <dd><i>{{product_type.description}}</i></dd>
      </dl>
      <ol>
        <h4>Items</h4>
          {% for product in product_type.product.all %}
            {% if product.owner.user != user %}
              <li><strong><a href='{{product.get_absolute_url}}'>{{product.name}} </strong> from {{product.owner.display_name}}</a>:<i>({{product.status}})</i></li>
              <ul>
                <li>{{product.description}}
              </ul>
            {% endif %}
          {% endfor %}
      </ol>
      <a href="{% url 'merchstore:cart' %}">Cart</a>
    {% endfor %}


{% else %}
  <h2>All Products</h2>
    {% for product_type in object_list %}
    <dl>
      <dt><h3>{{product_type}}</h3></dt>
      <dd><i>{{product_type.description}}</i></dd>
    </dl>
    <ol>
      <h4>Items</h4>
        {% for product in product_type.product.all %}
        <li><strong><a href='{{product.get_absolute_url}}'>{{product.name}} </strong> from {{product.owner.display_name}}</a>:<i>({{product.status}})</i></li>
              <ul>
                <li>{{product.description}}
              </ul>
        {% endfor %}
    </ol>
    {% endfor %}
    <a href="{% url 'merchstore:cart' %}">Cart</a>
  {% endif %}
  </ul>

{% endblock %}

hobbysite/merchstore/templates/merchstore/productform.html
{% extends 'merchstore/base.html' %}
{% load static %}
{% block title %} Product Form {% endblock %}

{% block content %}

<h2> Product Form </h2>

<form method = "POST" enctype = "multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type = "submit">Submit</button>
</form>


{% endblock %}

hobbysite/merchstore/templates/merchstore/transactions.html
{% extends 'merchstore/base.html' %}
{% load static %}
{% block title %} Transactions {% endblock %}
{% block content %}

<ul>
<h2>Your Transactions</h2>
  {% for buyer in buyers %}
    <dl>
      {% if buyer.user != user %}
      <dt><h3>Bought by {{buyer.display_name}}</h3></dt>
      {% endif %}
    </dl>
    <ol>
    {% for transaction in object_list %}
      {% if transaction.buyer == buyer %}
        {% if transaction.product.owner.user == user %}
          <li><strong>{{transaction.product.name}} ({{transaction.status}})</strong> </li>
            <ul>
              <li>{{transaction.amount}} item(/s)</li>
            </ul>
        {% endif %}
      {%endif%}
    {% endfor %}
    </ol>
  {% endfor %}
</ul>
<a href="{% url 'merchstore:items' %}">Return to Product Listings</a>
{% endblock %}